Enable null checker on exception files
planetarium/libplanet pull request #1021
Opened 2020-09-27 19:26 UTC by dahlia

Enable null checker on exceptions files.  This contributes to #458.

Total files:

```console
$ find Libplanet/ -name '*.cs' | wc -l
187
```

Files that enable null checker (39%):

```console
$ git grep '#nullable enable' Libplanet/ | wc -l
73
```

Note that it was before (19%):

```console
$ git grep '#nullable enable' Libplanet/ | wc -l
37
```

2020-09-27 23:47 UTC, moreal approved these changes
LGTM 😎

2020-09-27 23:51 UTC, longfin submitted a review, later dismissed

2020-09-28 01:05 UTC, limebell requested changes

2020-09-28 01:05 UTC, limebell commented on CHANGES.md
> + -  Removed constructors from `InvalidMessageException` class.
```suggestion
 -  Removed constructors from `InvalidMessageException` class.  [[#1021]]
```

2020-09-28 03:32 UTC, dahlia commented
@planetarium/libplanet Added a missing reference to the PR number.  Please review this again!

2020-09-28 03:36 UTC, riemannulus approved these changes

2020-09-28 03:36 UTC, moreal approved these changes

2020-09-28 03:40 UTC, limebell approved these changes

2020-09-28 04:45 UTC, earlbread approved these changes

2020-09-28 04:54 UTC, merged