Release 0.10.0
planetarium/libplanet pull request #1053
Opened 2020-10-26 03:35 UTC by riemannulus

- Release 0.10.0

2020-10-26 03:36 UTC, earlbread approved these changes

2020-10-26 04:33 UTC, dahlia commented
Could we include #1050, which adjusts #1039 (naming & defaulting), as well in this release?

2020-10-26 04:36 UTC, limebell approved these changes

2020-10-26 05:37 UTC, riemannulus commented
@dahlia I'll hold for that

2020-10-26 06:17 UTC, area363 submitted a review, later dismissed

2020-10-26 11:57 UTC, dahlia requested changes
- [x] Could you include the patch #1050 too, which is merged today?
- [x] [As I said our Discord server][1], there seem some outdated changelogs to polish.

[1]: https://discord.com/channels/539405872346955788/596226080549896239/770170692842553384

2020-10-26 12:00 UTC, riemannulus commented
@dahlia 👌

2020-10-27 01:15 UTC, limebell requested changes

2020-10-27 01:15 UTC, limebell commented on CHANGES.md
> +Released on October 26, 2020.
```suggestion
Released on October 27, 2020.
```
😂

2020-10-27 01:27 UTC, riemannulus commented on CHANGES.md
> +Released on October 26, 2020.
😭

2020-10-27 04:33 UTC, riemannulus commented on CHANGES.md
> +Released on October 26, 2020.
https://github.com/planetarium/libplanet/pull/1053/commits/6e2893fe5273167e97d687c37353fc2778f9e7e1 changed

2020-10-27 04:34 UTC, riemannulus commented
@dahlia https://github.com/planetarium/libplanet/pull/1053/commits/6e2893fe5273167e97d687c37353fc2778f9e7e1 Please review again!

2020-10-27 04:38 UTC, limebell approved these changes

2020-10-27 04:40 UTC, earlbread approved these changes

2020-10-27 04:40 UTC, dahlia commented
Instead of having a merge commit (fed5e4ef7d605c606a52a0e31efa65fcba3f536f), could you rebase this on the current main?

2020-10-27 04:46 UTC, dahlia approved these changes
:shipit:

2020-10-27 04:51 UTC, moreal approved these changes

2020-10-27 04:52 UTC, area363 approved these changes

2020-10-27 04:57 UTC, earlbread approved these changes

2020-10-27 05:01 UTC, limebell approved these changes

2020-10-27 05:11 UTC, dahlia commented
The repetitive timeout on a Windows job seems the same to <https://github.com/planetarium/libplanet/pull/1050#issuecomment-716500477>.  IMHO it's okay to merge without retrying it.

2020-10-27 05:13 UTC, merged