Fix `new Null()` to `default(Null)`
planetarium/libplanet pull request #1263
Opened 2021-04-22 08:44 UTC by boscohyun

There is only line to construct the `Null` struct with `new Null()` and we need change it to `default(Null)` if possible.

2021-04-22 08:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/planetarium/libplanet?pullRequest=1263) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/planetarium/libplanet?pullRequest=1263) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/planetarium/libplanet?pullRequest=1263) it.</sub>

2021-04-22 08:53 UTC, dahlia reviewed
Could you sign our CLA?  (It's necessary only for the first time.)

This also needs to be rebased on the up-to-date _main_ branch.

2021-04-22 08:54 UTC, dahlia commented
Relevant issue: <https://github.com/planetarium/bencodex.net/issues/20>.

2021-04-22 09:29 UTC, longfin approved these changes

2021-04-28 05:08 UTC, riemannulus approved these changes

2021-05-07 06:18 UTC, dahlia commented
It would be better if *Bencodex* packaged is upgraded to the latest version and `Null.Value` field is used instead after <https://github.com/planetarium/bencodex.net/pull/37> is merged.

2021-05-07 07:09 UTC, limebell approved these changes

2021-05-18 01:15 UTC, limebell commented
Can you please update this branch? @boscohyun

2021-05-18 01:22 UTC, dahlia requested changes
As *Bencodex* package now has `Null.Value` property (see also <https://github.com/planetarium/bencodex.net/pull/37>), we don't need to suppress `SA1129` warning anymore.  You can simply use `Null.Value` instead of `default(Null)` or `new Null()`.

@boscohyun Could you rebase this on the up-to-date *main* branch, and use `Null.Value` instead?

2021-05-18 02:26 UTC, dahlia commented
Oh, I already worked on this in the commit 2c75b0f9c1ad18e4d0fcf054bf9222fe98670516.  This pull request seems now unnecessary.  I close this.  Thanks @boscohyun!

2021-05-18 02:26 UTC, closed without merging

2021-05-18 02:27 UTC, boscohyun commented
> As _Bencodex_ package now has `Null.Value` property (see also [planetarium/bencodex.net#37](https://github.com/planetarium/bencodex.net/pull/37)), we don't need to suppress `SA1129` warning anymore. You can simply use `Null.Value` instead of `default(Null)` or `new Null()`.
> 
> @boscohyun Could you rebase this on the up-to-date _main_ branch, and use `Null.Value` instead?

@dahlia That's good news! Now there is no longer any need to worry between `default(Null)` and `new Null()`. Thank you!
I'll close this PR.