`IActionContext.BlockHash` property
planetarium/libplanet pull request #1296
Opened 2021-05-13 09:37 UTC by dahlia

Closes <https://github.com/planetarium/libplanet/issues/1295>.

2021-05-13 09:45 UTC, limebell requested changes

2021-05-13 09:45 UTC, limebell commented on CHANGES.md
> +>>>>>>> 9d9bcd87b (IActionContext.BlockHash property)
```suggestion
[#1289]: https://github.com/planetarium/libplanet/pull/1289
[#1295]: https://github.com/planetarium/libplanet/issues/1295
[#1296]: https://github.com/planetarium/libplanet/pull/1296
```
Conflict sign still exists 👀

2021-05-13 09:46 UTC, dahlia commented on CHANGES.md
> +>>>>>>> 9d9bcd87b (IActionContext.BlockHash property)
![Amended.](https://s3.orbi.kr/data/file/united/8d115e92195ceaf5776bc6efce932277.jpg)

2021-05-13 09:53 UTC, area363 approved these changes
🙇

2021-05-13 11:10 UTC, limebell approved these changes

2021-05-14 02:12 UTC, dahlia commented
/rebase

2021-05-14 02:52 UTC, area363 approved these changes

2021-05-14 04:43 UTC, dahlia commented
@planetarium/libplanet Please take a look again.

2021-05-14 05:36 UTC, longfin approved these changes

2021-05-14 05:55 UTC, merged