Explicit package reference to Microsoft.Bcl.AsyncInterfaces
planetarium/libplanet pull request #1400
Opened 2021-07-26 04:26 UTC by greymistcube

On VSCode, the following errors persist:

```
The type 'IAsyncEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [Libplanet.Tests]
```

[AsyncEnumerator](https://www.nuget.org/packages/AsyncEnumerator/) requires [Microsoft.Bcl.AsyncInterfaces](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/) only on certain target frameworks, but dependency does not seem to resolve properly with OmniSharp on VSCode.

This might not be a proper solution, but does get rid of numerous pesky error messages on VSCode. 🙃

2021-07-29 01:00 UTC, greymistcube commented
/rebase

2021-07-30 01:41 UTC, greymistcube commented
/rebase

2021-07-30 01:52 UTC, longfin approved these changes

2021-07-30 02:05 UTC, dahlia submitted a review, later dismissed

2021-07-30 02:19 UTC, dahlia approved these changes

2021-07-30 03:29 UTC, dahlia commented
It seems to fail to build on Windows Mono:

      System.MissingMethodException : Method not found: System.Collections.Generic.IAsyncEnumerable`1<System.ValueTuple`2<long, Libplanet.Blocks.BlockHash>> Libplanet.Net.Swarm`1.GetDemandBlockHashes(Libplanet.Blockchain.BlockChain`1<!0>,System.Collections.Generic.IList`1<System.ValueTuple`2<Libplanet.Net.BoundPeer, long>>,System.IProgress`1<Libplanet.Net.PreloadState>,System.Threading.CancellationToken)
      Stack Trace:
          at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in <32116eccb94d4ed685ca661d98e36637>:0 
          at Libplanet.Tests.Net.SwarmTest.GetDemandBlockHashes () [0x0001c] in <8791e2247da141dd8f7bb8f6471d404a>:0 
          at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
          at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <32116eccb94d4ed685ca661d98e36637>:0

2021-07-30 03:30 UTC, dahlia requested changes
It seems to fail to build on Windows Mono:

      System.MissingMethodException : Method not found: System.Collections.Generic.IAsyncEnumerable`1<System.ValueTuple`2<long, Libplanet.Blocks.BlockHash>> Libplanet.Net.Swarm`1.GetDemandBlockHashes(Libplanet.Blockchain.BlockChain`1<!0>,System.Collections.Generic.IList`1<System.ValueTuple`2<Libplanet.Net.BoundPeer, long>>,System.IProgress`1<Libplanet.Net.PreloadState>,System.Threading.CancellationToken)
      Stack Trace:
          at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in <32116eccb94d4ed685ca661d98e36637>:0 
          at Libplanet.Tests.Net.SwarmTest.GetDemandBlockHashes () [0x0001c] in <8791e2247da141dd8f7bb8f6471d404a>:0 
          at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
          at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <32116eccb94d4ed685ca661d98e36637>:0

2021-07-30 07:39 UTC, greymistcube commented
Updated with a reduced scope.

2021-07-30 07:54 UTC, longfin approved these changes

2021-08-04 01:23 UTC, limebell approved these changes

2021-08-04 01:38 UTC, merged