Build Libplanet.Tools executables for linux-arm64 & win-arm64
planetarium/libplanet pull request #1650
Opened 2021-12-08 04:14 UTC by dahlia

2021-12-08 04:16 UTC, riemannulus submitted a review, later dismissed

2021-12-08 05:01 UTC, dahlia commented
Apparently there is an issue on build… I don't merge it right now.

2021-12-15 01:01 UTC, dahlia commented
I rebased this and fixed the build. Please take a look again!

2021-12-15 01:13 UTC, longfin approved these changes

2021-12-15 04:49 UTC, riemannulus approved these changes

2022-02-21 04:46 UTC, longfin requested changes
It seems to have conflicts.

2022-04-27 19:24 UTC, closed without merging