Comment `Context` and `ConsensusContext`
planetarium/libplanet pull request #2124
Opened 2022-06-29 07:16 UTC by colibrishin

🌳

2022-06-29 08:00 UTC, limebell commented on Libplanet.Net/Consensus/ConsensusContext.cs
> +        /// Starts next height.
```suggestion
        /// Starts a consensus for a block of index <paramref name="height/>.
```

2022-06-29 08:01 UTC, limebell commented on Libplanet.Net/Consensus/ConsensusContext.cs
> +        /// <exception cref="InvalidHeightIncreasingException">Throws if given height is not same as
```suggestion
        /// <exception cref="InvalidHeightIncreasingException">Thrown if given height is not same as
```

2022-06-29 08:01 UTC, limebell commented on Libplanet.Net/Consensus/ConsensusContext.cs
> +        /// <remarks>This method is also called when the tip of <see cref="BlockChain{T}"/> is
```suggestion
        /// <remarks>This method is also called when the tip of the <see cref="BlockChain{T}"/> is
```

2022-06-29 08:03 UTC, limebell commented on Libplanet.Net/Consensus/ConsensusContext.cs
> +        /// <see cref="BlockChain{T}"/>.
```suggestion
        /// Committing the block to the <see cref="BlockChain{T}"/>.
```
Description is out of context, duplication of <remarks> section.

2022-06-29 08:04 UTC, limebell commented on Libplanet.Net/Consensus/ConsensusContext.cs
> +        /// <param name="block">A block to committing to <see cref="BlockChain{T}"/>.
```suggestion
        /// <param name="block">A <see cref="Block{T}"/> to committing to the <see cref="BlockChain{T}"/>.
```

2022-06-29 08:26 UTC, colibrishin commented on Libplanet.Net/Consensus/ConsensusContext.cs
> +        /// will be voted by consensus, and used for proposing a block
I was thinking about `BlockChain<T>.ProposeBlock()`. `ConsensusContext` does not use directly but `Context` does, and it seems to be motioned.
https://github.com/planetarium/libplanet/blob/5de07cbc7794e19ee5c1ee3211e198db87de245f/Libplanet/Blockchain/BlockChain.MineBlock.cs#L236-L245
https://github.com/planetarium/libplanet/blob/5de07cbc7794e19ee5c1ee3211e198db87de245f/Libplanet.Net/Consensus/Context.cs#L461-L470

2022-06-29 09:13 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// A timeout task for a round if <see cref="ConsensusCommit"/> is received +2/3 Any but has
```suggestion
        /// A timeout task for a round if <see cref="ConsensusCommit"/> is received +2/3 any but has
```

2022-06-29 09:14 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="height">A height that timeout task is scheduled for.
```suggestion
        /// <param name="height">A height that the timeout task is scheduled for.
```

2022-06-29 09:15 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="round">A round that timeout task is scheduled for.
```suggestion
        /// <param name="round">A round that the timeout task is scheduled for.
```

2022-06-29 09:15 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="height">A height that timeout task is scheduled for.
```suggestion
        /// <param name="height">A height that the timeout task is scheduled for.
```

2022-06-29 09:15 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="round">A round that timeout task is scheduled for.
```suggestion
        /// <param name="round">A round that the timeout task is scheduled for.
```

2022-06-29 09:15 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="height">A height that timeout task is scheduled for.
```suggestion
        /// <param name="height">A height that the timeout task is scheduled for.
```

2022-06-29 09:16 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="round">A round that timeout task is scheduled for.
```suggestion
        /// <param name="round">A round that the timeout task is scheduled for.
```

2022-06-29 09:17 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// Check whether the round has +2/3 <see cref="ConsensusCommit"/>.
```suggestion
        /// Check whether the round has +2/3 <see cref="ConsensusCommit"/> for the <see cref="Block{T}"/> of hash <paramref name="hash"/>.
```

2022-06-29 09:18 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// Check whether the round has +2/3 <see cref="ConsensusVote"/>.
```suggestion
        /// Check whether the round has +2/3 <see cref="ConsensusVote"/> for the <see cref="Block{T}"/> of hash <paramref name="hash"/>..
```

2022-06-29 09:20 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// Consume the every <see cref="ConsensusMessage"/> in message queue.
```suggestion
        /// Consume every <see cref="ConsensusMessage"/> in the message queue.
```

2022-06-29 09:20 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// Get the proposed block and valid round of given round.
```suggestion
        /// Get the proposed block and valid round of the given round.
```

2022-06-29 09:21 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <returns>Returns a tuple of proposer and valid round, or otherwise returns a tuple of
```suggestion
        /// <returns>Returns a tuple of proposer and valid round. If proposal for the round does not exist, returns a tuple of
```

2022-06-29 09:21 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// null and null.
```suggestion
        /// <c>null</c> and <c>null</c>.
```

2022-06-29 09:25 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="step">A new step.
```suggestion
        /// <param name="step">A new step to set.
```

2022-06-29 09:28 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <see cref="ConsensusCommit"/>.
```suggestion
        /// Creates a <see cref="Vote"/> instance for <see cref="ConsensusVote"/> or
        /// <see cref="ConsensusCommit"/> for the <paramref name="round"/> and the <paramref name="hash"/>.
```

Additionally, how about remove `height` param? It seems only `Height` is used.

2022-06-29 09:29 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="block">A block to validate.
```suggestion
        /// <param name="block">A <see cref="Block{T}"/> to validate.
```

2022-06-29 09:29 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <returns>returns <c>true</c> if block is valid, or otherwise returns <c>false</c>.
```suggestion
        /// <returns>Returns <c>true</c> if block is valid, or otherwise returns <c>false</c>.
```

2022-06-29 09:31 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="round">A round.</param>
```suggestion
        /// <param name="round">A round to get proposer.</param>
```

2022-06-29 09:32 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <returns>Returns proposer's <see cref="PublicKey"/> in round.
```suggestion
        /// <returns>Returns designated proposer's <see cref="PublicKey"/> for the <paramref name="round"/>.
```

2022-06-29 09:32 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <returns> A new <see cref="Block{T}"/>.
```suggestion
        /// <returns>A new <see cref="Block{T}"/>.
```

2022-06-29 09:33 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// Add a <see cref="ConsensusMessage"/>. The message will be validated before adding.
```suggestion
        /// Validate the given <paramref name="message"/> and add it to the message queue.
```

2022-06-29 09:35 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="message">a <see cref="ConsensusMessage"/> that will be handled.
```suggestion
        /// <param name="message">A <see cref="ConsensusMessage"/> that will be handled.
```

2022-06-29 09:36 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <exception cref="InvalidHeightMessageException">Height of message and context height
```suggestion
        /// <exception cref="InvalidHeightMessageException">Thrown when the height of the message and the context height
```

2022-06-29 09:36 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <exception cref="InvalidProposerProposeMessageException"><see cref="ConsensusPropose"/>
```suggestion
        /// <exception cref="InvalidProposerProposeMessageException">Thrown when the <see cref="ConsensusPropose"/>
```

2022-06-29 09:36 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// message has proposer that is not proposer of current round.
```suggestion
        /// message has proposer that is not proposer of the current round.
```

2022-06-29 09:36 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <exception cref="InvalidBlockProposeMessageException"><see cref="ConsensusPropose"/>
```suggestion
        /// <exception cref="InvalidBlockProposeMessageException">Thrown when the <see cref="ConsensusPropose"/>
```

2022-06-29 09:37 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <exception cref="InvalidValidatorVoteMessageException">The signature of
```suggestion
        /// <exception cref="InvalidValidatorVoteMessageException">Thrown when the signature of the
```

2022-06-29 09:38 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="round">A round.</param>
```suggestion
        /// <param name="round">A round to get the timeout.</param>
```

2022-06-29 09:38 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="round">A round.</param>
```suggestion
        /// <param name="round">A round to get the timeout.</param>
```

2022-06-29 09:38 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// Get the timeout of <see cref="Libplanet.Net.Consensus.Step.PreCommit"/> in given round.
```suggestion
        /// Get the timeout of <see cref="Libplanet.Net.Consensus.Step.PreCommit"/> in the given round.
```

2022-06-29 09:39 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// Get the timeout of <see cref="Libplanet.Net.Consensus.Step.Propose"/> in given round.
```suggestion
        /// Get the timeout of <see cref="Libplanet.Net.Consensus.Step.Propose"/> in the given round.
```

2022-06-29 09:39 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// Get the timeout of <see cref="Libplanet.Net.Consensus.Step.PreVote"/> in given round.
```suggestion
        /// Get the timeout of <see cref="Libplanet.Net.Consensus.Step.PreVote"/> in the given round.
```

2022-06-29 09:39 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <param name="round">A round.</param>
```suggestion
        /// <param name="round">A round to get the timeout.</param>
```

2022-06-29 09:40 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// Add received message to message queue.
```suggestion
        /// Add received message to the message queue.
```

2022-06-29 09:41 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// Returns a <see cref="Libplanet.Consensus.VoteSet"/> of given round.
```suggestion
        /// Returns a <see cref="Libplanet.Consensus.VoteSet"/> of the given round.
```

2022-06-29 09:42 UTC, limebell commented on Libplanet.Net/Consensus/Context.cs
> +        /// <returns>A <see cref="Task"/> representing the asynchronous operation. This task
```suggestion
        /// <returns>An awaitable task without value. This task
```

2022-06-30 09:08 UTC, limebell requested changes
Almost over...

2022-07-04 01:57 UTC, limebell approved these changes
It looks good to me, but please wait for @riemannulus' review before merge.

2022-07-04 04:41 UTC, riemannulus approved these changes
Good Job

2022-07-04 04:46 UTC, merged