Add docstring for `BlockChain.ProposeBlock()`
planetarium/libplanet pull request #2129
Opened 2022-06-30 08:23 UTC by limebell

2022-06-30 10:05 UTC, colibrishin requested changes

2022-06-30 10:05 UTC, colibrishin commented on Libplanet/Blockchain/BlockChain.MineBlock.cs
> +        /// accept.  See also <see cref="IBlockPolicy{T}.GetMaxTransactionsPerBlock(long)"/>.
```suggestion
        /// accept. See also <see cref="IBlockPolicy{T}.GetMaxTransactionsPerBlock(long)"/>.
```

2022-06-30 10:05 UTC, colibrishin commented on Libplanet/Blockchain/BlockChain.MineBlock.cs
> +        /// that a block can accept per signer.  See also
```suggestion
        /// that a block can accept per signer. See also
```

2022-06-30 10:05 UTC, colibrishin commented on Libplanet/Blockchain/BlockChain.MineBlock.cs
> +        /// priority to belong to the block.  No certain priority by default.</param>
```suggestion
        /// <param name="txPriority">An optional comparer for prioritizing certain transactions
        /// that are belong to the block. No certain priority by default.</param>
```

2022-06-30 10:05 UTC, colibrishin commented on Libplanet/Blockchain/BlockChain.MineBlock.cs
> +        /// <param name="lastCommit"><see cref="BlockCommit"/> of previous <see cref="Block{T}"/>.
```suggestion
        /// <param name="lastCommit">A <see cref="BlockCommit"/> of previous <see cref="Block{T}"/>.
```

2022-06-30 10:05 UTC, colibrishin commented on Libplanet/Blockchain/BlockChain.MineBlock.cs
> +        /// <param name="cancellationToken">A cancellation token used to propagate notification
```suggestion
        /// <param name="cancellationToken">A cancellation token used to propagates notification
```

2022-06-30 10:05 UTC, colibrishin commented on Libplanet/Blockchain/BlockChain.MineBlock.cs
> +        /// Proposes a next <see cref="Block{T}"/> using staged <see cref="Transaction{T}"/>s.
```suggestion
        /// Proposes a next <see cref="Block{T}"/> with staged <see cref="Transaction{T}"/>s.
```

2022-06-30 10:05 UTC, colibrishin commented on Libplanet/Blockchain/BlockChain.MineBlock.cs
> +        /// Proposes a next <see cref="Block{T}"/> using staged <see cref="Transaction{T}"/>s.
```suggestion
        /// Proposes a next <see cref="Block{T}"/> with staged <see cref="Transaction{T}"/>s.
```

2022-07-01 06:02 UTC, limebell commented on Libplanet/Blockchain/BlockChain.MineBlock.cs
> +        /// priority to belong to the block.  No certain priority by default.</param>
It's copy of `BlockChain.Mine()` docstring. Do you think it should be changed to?

2022-07-01 06:05 UTC, limebell commented on Libplanet/Blockchain/BlockChain.MineBlock.cs
> +        /// accept.  See also <see cref="IBlockPolicy{T}.GetMaxTransactionsPerBlock(long)"/>.
This is intended, it's our convention for writing docstring and separate paragraphs.
See also:
https://github.com/planetarium/libplanet/blob/main/Libplanet/Blockchain/BlockChain.MineBlock.cs#L83

2022-07-01 06:09 UTC, limebell commented on Libplanet/Blockchain/BlockChain.MineBlock.cs
> +        /// that this operation should be canceled.</param>
I'm not really a master of English grammar, many use case in our docstrings for the parameter `cancellationToken` is this.

2022-07-01 06:12 UTC, colibrishin commented on Libplanet/Blockchain/BlockChain.MineBlock.cs
> +        /// that this operation should be canceled.</param>
Oh, former grammer was right.

2022-07-01 06:20 UTC, colibrishin approved these changes

2022-07-01 06:31 UTC, merged