Add get random seed method
planetarium/libplanet pull request #2236
Opened 2022-08-23 08:28 UTC by hunkim98

Add get random seed method

2022-08-24 11:22 UTC, longfin requested changes
And, we need to a mention about `ActionEvaluator<T>.GenerateRandomSeed()` in `CHANGES.md`. 😄

2022-08-24 11:22 UTC, longfin commented on CHANGES.md
> +>>>>>>> f0d0f666a (Add test code and add info to changes.md)
```suggestion
[#1972]: https://github.com/planetarium/libplanet/issues/1972
[#2173]: https://github.com/planetarium/libplanet/pull/2173
[#2179]: https://github.com/planetarium/libplanet/pull/2179
[#2183]: https://github.com/planetarium/libplanet/pull/2183
```

2022-08-24 11:22 UTC, longfin commented on Libplanet.Tests/Action/ActionEvaluatorTest.cs
> +            }
```suggestion
            using SHA1 hasher = SHA1.Create())
            hashedSignature = hasher.ComputeHash(signature);
```

[using statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement) seems enough in this case.

2022-08-24 11:22 UTC, longfin commented on Libplanet.Tests/Action/ActionEvaluatorTest.cs
> +            var signature = new byte[]
```suggestion
            byte[] signature =
```
Just for consistency with above😅

2022-08-30 10:46 UTC, hunkim98 commented
Changes.md has been modified. GetRandomSeed static method has been added under Added APIs

2022-09-02 13:04 UTC, colibrishin commented on CHANGES.md
> + -  Added `ActionEvaluator<T>.GenerateRandomSeed()` static method.  [[#2236]]
```suggestion
 -  Added `ActionEvaluator<T>.GenerateRandomSeed()` static method.  [[#2236]]
 
```

2022-09-04 02:52 UTC, longfin commented on CHANGES.md
> +[#1972]: https://github.com/planetarium/libplanet/issues/1972
```suggestion
```

2022-09-04 02:53 UTC, longfin commented on CHANGES.md
> +[#2236]: https://github.com/planetarium/libplanet/pull/2236
```suggestion
[#2131]: https://github.com/planetarium/libplanet/issues/2131
[#2236]: https://github.com/planetarium/libplanet/pull/2236
```

2022-09-04 02:53 UTC, longfin commented on CHANGES.md
> + -  Added `ActionEvaluator<T>.GenerateRandomSeed()` static method.  [[#2236]]
```suggestion
 -  Added `ActionEvaluator<T>.GenerateRandomSeed()` static method.  [[#2131], [#2236]]
```

2022-09-04 02:54 UTC, longfin submitted a review, later dismissed

2022-09-04 04:32 UTC, riemannulus requested changes

2022-09-04 04:32 UTC, riemannulus commented on Libplanet.Tests/Action/ActionEvaluatorTest.cs
> +            using SHA1 hasher = SHA1.Create())
This is a typo, right?
```suggestion
            using SHA1 hasher = SHA1.Create()
```

2022-09-21 07:21 UTC, longfin approved these changes

2022-09-22 05:44 UTC, longfin commented on CHANGES.md
> + -  Added `ActionEvaluator<T>.GenerateRandomSeed()` static method.  [[#2131], [#2236]]
```suggestion
 -  Added `ActionEvaluator<T>.GenerateRandomSeed()` static method.  
    [[#2131], [#2236]]
```

2022-09-28 02:27 UTC, riemannulus approved these changes

2022-09-28 02:28 UTC, riemannulus commented
PTAL 🙏 @longfin @colibrishin

2022-09-28 03:43 UTC, colibrishin approved these changes
LGTM

2022-09-28 05:33 UTC, longfin approved these changes

2022-09-28 06:00 UTC, merged