Introduce vote query
planetarium/libplanet pull request #2622
Opened 2022-12-10 09:02 UTC by OnedgeLee

### Needs
Query for fetching recent validator's consensus activities is needed.

### Changes
Queries that fetch some `Vote` information from `BlockCommit` has been implemented.

### Related issues
- https://github.com/planetarium/libplanet/issues/2621

2022-12-12 13:54 UTC, longfin commented on Libplanet.Explorer.Tests/Queries/VoteQueryTest.cs
> +        public async void CountVotesQuery()
```suggestion
        public async Task CountVotesQuery()
```

2022-12-12 13:54 UTC, longfin commented on Libplanet.Explorer/Queries/VoteQuery.cs
> +        public VoteQuery(IBlockChainContext<T> chainContext)
```suggestion
        public VoteQuery(BlockChain<T> blockChain, IStore store)
```

In most cases, `IBlockChainContext<T>` isn't necessary.  😅

2022-12-12 13:54 UTC, longfin commented on Libplanet.Explorer/Queries/VoteQuery.cs
> +        internal IEnumerable<Vote> ListValidatorVotes(
I think that it may be okay without this method. 🤔

2022-12-12 13:54 UTC, longfin commented on Libplanet.Explorer/Queries/VoteQuery.cs
> +        internal IEnumerable<VoteCount> CountVotes(
How about unifying `CountVotes()` and `CountValidatorVotes()` and replacing its parameters from `bool`, `long`, `long?` to `IEnumerable<Vote>`?

2022-12-12 13:54 UTC, longfin commented on Libplanet.Explorer/Queries/VoteQuery.cs
> +                    result = result.Concat(store.GetBlockCommit(index.value).Votes).ToList();
```suggestion
                    result.AddRange(store.GetBlockCommit(index.value).Votes);
```

2022-12-12 13:54 UTC, longfin commented on Libplanet.Explorer/Queries/ExplorerQuery.cs
> +            Field<VoteQuery<T>>("previousVoteQuery", resolve: context => new { });
```suggestion
            Field<VoteQuery<T>>("voteQuery", resolve: context => new { });
```

As the type suggests, `voteQuery` seems fine. (or `blockVoteQuery`?)

2022-12-12 13:54 UTC, longfin commented on Libplanet.Explorer.Tests/Queries/VoteQueryTest.cs
> +        public async void ValidatorVotesQuery(int validatorIdx)
```suggestion
        public async Task ValidatorVotesQuery(int validatorIdx)
```

2022-12-12 13:54 UTC, longfin commented on Libplanet.Explorer.Tests/Queries/VoteQueryTest.cs
> +        public async void VotesQuery()
```suggestion
        public async Task VotesQuery()
```

2022-12-12 13:54 UTC, longfin commented on Libplanet.Explorer.Tests/Queries/VoteQueryTest.cs
> +        public async void CountValidatorVotesQuery(int validatorIdx)
```suggestion
        public async Task CountValidatorVotesQuery(int validatorIdx)
```

2022-12-12 17:45 UTC, greymistcube commented on Libplanet.Explorer/Queries/VoteQuery.cs
> +                var votes = store.GetBlockCommit(index.value)?.Votes;
`IStore` only has `BlockCommit`s for caching. I think `BlockChain<T>.GetBlockCommit()` should be used instead.

2022-12-12 17:51 UTC, greymistcube commented on Libplanet.Explorer/Queries/VoteQuery.cs
> +                    result = result.Concat(store.GetBlockCommit(index.value).Votes).ToList();
```suggestion
                if (store.GetBlockCommit(index.value)?.Votes is { } votes)
                {
                    result.AddRange(votes);
```

We already know `votes` is not `null`. 😗

2023-02-01 05:29 UTC, longfin requested changes
The build seems to fail, could you check?

2023-02-01 05:29 UTC, longfin commented on Libplanet.Explorer/GraphTypes/VoteType.cs
> +                description: "Hight of the consensus voted.",
```suggestion
                description: "Height of the consensus voted.",
```

2023-02-01 08:16 UTC, OnedgeLee commented
I've removed `VoteQuery`, since it's too specific to be a part of `Libplanet`. Instead, I've added `BlockCommitType` as a part of `BlockType`, make it possible to query `Vote`s on `BlockQuery`.

2023-02-01 08:51 UTC, limebell approved these changes

2023-02-01 09:06 UTC, OnedgeLee commented
> The build seems to fail, could you check?

Fixed

2023-02-01 09:07 UTC, merged