Add ValidatorPower property to Vote class
planetarium/libplanet pull request #3855
Opened 2024-06-28 07:25 UTC by s2quake

2024-06-28 09:11 UTC, limebell commented
Seems missing commit 93127cde42623af060cf1ca81ffadc7cc0d14003 which may cause critical issue.

2024-06-28 09:54 UTC, s2quake commented
> Seems missing commit [93127cd](https://github.com/planetarium/libplanet/commit/93127cde42623af060cf1ca81ffadc7cc0d14003) which may cause critical issue.

https://github.com/planetarium/libplanet/commit/93127cde42623af060cf1ca81ffadc7cc0d14003 has been applied via cherry-pick. -> https://github.com/planetarium/libplanet/pull/3855/commits/fcb2e634aeca78a204880afca5627a6708f11dbc

2024-07-01 05:33 UTC, limebell requested changes
Can you bring changelog for this change too?

2024-07-01 08:13 UTC, limebell approved these changes

2024-07-04 05:35 UTC, limebell approved these changes

2024-07-04 05:47 UTC, merged