PolicyActionsRegistry
planetarium/libplanet pull request #3882
Opened 2024-07-16 02:21 UTC by s2quake

2024-07-19 14:43 UTC, greymistcube commented
Changed the name `IsBlockAction` to `IsPolicyAction`. Having `BeginTxActions` and `EndTxActions` as "block action"s seemed non-sensical at this point. 🙄

2024-07-22 07:18 UTC, limebell requested changes

2024-07-22 07:18 UTC, limebell commented on src/Libplanet.Action/ActionEvaluator.cs
> +            bool isBlockAction,
```suggestion
            bool isPolicyAction,
```

2024-07-22 07:18 UTC, limebell commented on src/Libplanet.Action/ActionEvaluator.cs
> +                    isPolicyAction: isBlockAction,
```suggestion
                    isPolicyAction: isPolicyAction,
```

2024-07-22 07:30 UTC, s2quake commented on src/Libplanet.Action/ActionEvaluator.cs
> +            bool isBlockAction,
amended https://github.com/planetarium/libplanet/pull/3882/commits/84682b3a0f41697f4986c58a7e92ed86c6af30a1

2024-07-22 07:30 UTC, s2quake commented on src/Libplanet.Action/ActionEvaluator.cs
> +                    isPolicyAction: isBlockAction,
amended https://github.com/planetarium/libplanet/pull/3882/commits/84682b3a0f41697f4986c58a7e92ed86c6af30a1

2024-07-22 08:57 UTC, limebell approved these changes

2024-07-22 08:57 UTC, merged